//
// Created by Abhishek on 19-07-2017.
//

#ifndef PROJ_ANDROID_STUDIO_GLOBALS_H
#define PROJ_ANDROID_STUDIO_GLOBALS_H
#define SPLASH_SCREEN_DURATION 2
#define CUSTOM_GRAVITY 2
#define UP_VELOCITY 100
#define LINEAR_VELOCITY -90

#define BIRD_COLSION_BITID 001
#define OBSTACLE_COLISION_BITID 002
#define POINT_COLLISION_BITID 003


//int maxScore = 0;

#endif //PROJ_ANDROID_STUDIO_GLOBALS_H
